"""Assemble the AOR-004 context package for a local task."""

from __future__ import annotations

from pathlib import Path

from aor_cli.specs.store import SpecRecord
from aor_cli.tasks.store import TaskRecord, save_task
from aor_cli.workspace import aor_dir


def write_context_package(root: Path, spec: SpecRecord, task: TaskRecord) -> Path:
    bundle = spec.path.parent
    package_dir = aor_dir(root) / "packages" / task.id
    package_dir.mkdir(parents=True, exist_ok=True)

    agents = _read(root / "AGENTS.md")
    spec_md = _read(spec.path)
    acceptance = _read(bundle / "acceptance.md")
    evidence = _read(bundle / "evidence.md")
    adrs = _collect(root / "adr", "*.md")
    policies = _collect(root / "policies", "*.md")

    context = (
        f"# Context package — {task.id}\n\n"
        f"Generated by Agent On Rails for **{spec.id}**.\n\n"
        "Vague prompts are not sufficient. This package is the contract.\n\n"
        "## CURRENT TASK\n\n"
        f"- id: `{task.id}`\n"
        f"- spec: `{spec.id}`\n"
        f"- title: {task.title}\n"
        f"- status: {task.status}\n"
        f"- implementation repository: `{task.repository or '(set --workdir / name the sibling repo)'}`\n"
        f"- model tier: {task.model_tier} (cheap-first)\n\n"
        f"{task.description}\n\n"
        "## Rules\n\n"
        "- Implement only in the repository named by the spec — never in the control-plane docs tree.\n"
        "- Do not mark the spec DONE. Implementor ≠ reviewer.\n"
        "- Attach evidence listed in `evidence.md` before asking for human final review.\n"
        "- If the spec and the code disagree, the spec wins until a human revises it.\n\n"
        "## AGENTS.md\n\n"
        f"{agents}\n\n"
        "## SPEC\n\n"
        f"{spec_md}\n\n"
        "## ACCEPTANCE\n\n"
        f"{acceptance}\n\n"
        "## EVIDENCE REQUIRED\n\n"
        f"{evidence}\n\n"
        "## ADRs\n\n"
        f"{adrs}\n\n"
        "## Policies\n\n"
        f"{policies}\n"
    )
    context_path = package_dir / "CONTEXT.md"
    context_path.write_text(context, encoding="utf-8")

    prompt = (
        f"You are the Implementor on an Agent On Rails AI Team for {spec.id}.\n\n"
        f"Read `{context_path}` in full. That file is your only source of product authority.\n\n"
        "Do this:\n"
        f"1. Work in the sibling implementation repo `{task.repository or 'named by the spec'}`, not the control-plane repo.\n"
        "2. Stay inside the spec + acceptance. Do not expand scope.\n"
        "3. Implement, add the tests the spec names, and open a PR.\n"
        "4. Do not mark the spec DONE and do not review your own work.\n"
    )
    (package_dir / "prompt.md").write_text(prompt, encoding="utf-8")

    task.context_path = str(context_path)
    save_task(root, task)
    return context_path


def _read(path: Path) -> str:
    if not path.is_file():
        return f"_(missing {path.name})_"
    return path.read_text(encoding="utf-8").strip()


def _collect(directory: Path, pattern: str) -> str:
    if not directory.is_dir():
        return "_(none)_"
    parts: list[str] = []
    for path in sorted(directory.glob(pattern)):
        if path.name.startswith("."):
            continue
        parts.append(f"### {path.relative_to(directory.parent)}\n\n{path.read_text(encoding='utf-8').strip()}")
    return "\n\n".join(parts) if parts else "_(none)_"
